# Generated by Django 2.1.2 on 2022-05-20 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_remove_item_sample_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sample_1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='サンプル項目1 文字列'),
        ),
        migrations.AddField(
            model_name='item',
            name='sample_11',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sample_11', to=settings.AUTH_USER_MODEL, verbose_name='自己設定１\u3000プレイヤー'),
        ),
    ]
