# Generated by Django 2.1.2 on 2022-05-20 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_auto_20220520_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='sample_11',
        ),
        migrations.AddField(
            model_name='item',
            name='element_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='element_1', to=settings.AUTH_USER_MODEL, verbose_name='プレイヤー'),
        ),
        migrations.AddField(
            model_name='item',
            name='element_3',
            field=models.IntegerField(blank=True, choices=[(1, '戦場'), (2, '終点'), (3, 'ポケモンスタジアム2'), (2, 'すま村'), (2, '村と街'), (2, 'カロスポケモンリーグ'), (2, '小戦場')], null=True, verbose_name='ステージ'),
        ),
    ]
