# Generated by Django 2.1.2 on 2022-05-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220520_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sample_6',
            field=models.BooleanField(blank=True, null=True, verbose_name='サンプル項目6 ブール値'),
        ),
    ]
