# Generated by Django 2.1.2 on 2022-05-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_item_sample_6'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='sample_6',
        ),
        migrations.AddField(
            model_name='item',
            name='element_2',
            field=models.BooleanField(default=True, verbose_name='ガチ'),
        ),
    ]
