# Generated by Django 2.1.2 on 2022-05-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20220520_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='element_2',
            field=models.BooleanField(default=False, verbose_name='ガチ'),
        ),
        migrations.AlterField(
            model_name='item',
            name='element_3',
            field=models.IntegerField(blank=True, choices=[(1, '戦場'), (2, '終点'), (3, 'ポケモンスタジアム2'), (4, 'すま村'), (5, '村と街'), (6, 'カロスポケモンリーグ'), (7, '小戦場')], null=True, verbose_name='ステージ'),
        ),
    ]
