# Generated by Django 2.1.2 on 2022-05-20 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20220520_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='element_4',
            field=models.IntegerField(blank=True, choices=[(1, '戦場'), (2, '終点'), (3, 'ポケモンスタジアム2'), (4, 'すま村'), (5, '村と街'), (6, 'カロスポケモンリーグ'), (7, '小戦場')], null=True, verbose_name='ステージ'),
        ),
        migrations.AddField(
            model_name='item',
            name='element_5',
            field=models.BooleanField(default=False, verbose_name='ガチ'),
        ),
        migrations.AddField(
            model_name='item',
            name='element_6',
            field=models.IntegerField(blank=True, choices=[(1, '戦場'), (2, '終点'), (3, 'ポケモンスタジアム2'), (4, 'すま村'), (5, '村と街'), (6, 'カロスポケモンリーグ'), (7, '小戦場')], null=True, verbose_name='ステージ'),
        ),
        migrations.AlterField(
            model_name='item',
            name='element_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='element_1', to=settings.AUTH_USER_MODEL, verbose_name='プレイヤー1'),
        ),
        migrations.AlterField(
            model_name='item',
            name='element_2',
            field=models.IntegerField(blank=True, choices=[(1, '戦場'), (2, '終点'), (3, 'ポケモンスタジアム2'), (4, 'すま村'), (5, '村と街'), (6, 'カロスポケモンリーグ'), (7, '小戦場')], null=True, verbose_name='ステージ'),
        ),
        migrations.AlterField(
            model_name='item',
            name='element_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='element_3', to=settings.AUTH_USER_MODEL, verbose_name='プレイヤー2'),
        ),
    ]
