# Generated by Django 2.1.2 on 2022-05-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20220520_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='element_2',
            field=models.IntegerField(blank=True, choices=[(1, 'ディーディーコング'), (2, 'シュルク')], null=True, verbose_name='キャラ1'),
        ),
        migrations.AlterField(
            model_name='item',
            name='element_4',
            field=models.IntegerField(blank=True, choices=[(1, 'ディーディーコング'), (2, 'シュルク')], null=True, verbose_name='キャラ2'),
        ),
    ]
