# Generated by Django 2.1.2 on 2022-05-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20220520_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='element_4',
            field=models.IntegerField(blank=True, choices=[(1, 'カズヤ'), (2, 'パックマン'), (3, 'ガノンドロフ')], null=True, verbose_name='キャラ2'),
        ),
    ]
