# Generated by Django 2.1.2 on 2022-05-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20220520_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='element_1',
            field=models.IntegerField(blank=True, choices=[(1, '柿沼祐介'), (2, '楠一馬'), (3, '窪添永遠')], null=True, verbose_name='プレイヤー1'),
        ),
        migrations.AlterField(
            model_name='item',
            name='element_2',
            field=models.IntegerField(blank=True, choices=[(1, '柿沼祐介'), (2, '楠一馬'), (3, '窪添永遠')], null=True, verbose_name='プレイヤー2'),
        ),
    ]
