# Generated by Django 2.1.2 on 2022-05-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_item_element_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='element_7',
            field=models.IntegerField(blank=True, choices=[(1, 'プレイヤー1'), (2, 'プレイヤー2')], null=True, verbose_name='勝者'),
        ),
    ]
