# Generated by Django 2.1.2 on 2022-05-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_item_element_7'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='element_7',
            field=models.IntegerField(blank=True, choices=[(1, 'プレイヤー1'), (2, 'プレイヤー2')], null=True, verbose_name='じゃんけん勝者'),
        ),
    ]
